### ISSUE TITLE
Add missing parameters to documentation for budget summary endpoint

### ISSUE THREAD

**Issue by wigsgiw** [pocketsmith/api#1]
We need to add all available parameters to the documentation for `/v2/users/id/budget_summary`. Documentation is live up at https://developers.pocketsmith.com/reference#get_users-id-budget.

The missing parameters are all accepted as URL parameters, and include:

- `start_date` which is the requested start date for the budget summary
- `end_date` which is the requested end date for the budget summary
- `period` which is the analysis period for the budget summary, one of `%i(event literal weeks months years)`
- `interval` which is the interval that we want to apply to the period selected (e.g. 3 weeks etc). This is an integer that is only valid when `period` is one of `%i(weeks months years)`

**Comment by maknz** [comment]
Fixed by #3.
